Modificacion de diseño de pagina de error
angieAGL/login-test pull request #25
Opened 2023-04-06 00:36 UTC by angieAGL

2023-04-06 01:17 UTC, MarioLozanoM requested changes

2023-04-06 01:17 UTC, MarioLozanoM commented on src/ui/components/ErrorView.tsx
ya, esto no se puede llamar errorview xq no es una view para cualquier error o para todos los errores, es sólo para el 404, por último podemos llamarla NotFoundView

2023-04-06 01:17 UTC, MarioLozanoM commented on src/ui/components/ErrorView.tsx
la pagina de error 404 (y en general ninguna otra página de error) no deben tener header, es sólo la página de error splasheada en todo el navegador

2023-04-06 01:17 UTC, MarioLozanoM commented on src/ui/components/common/NavBar.tsx
si no estás navegando dentro de los cruds, la barra está mal y su div sólo abarca el alto de los menus pero no llega más abajo, tiene que seguir hasta el final de la página, esto sí está bien cuando estas dentro de un mantenimiento

2023-04-06 01:22 UTC, angieAGL commented on src/ui/components/ErrorView.tsx
Ahh oki, es que yo seguí lo que salia en figma por eso

2023-04-06 06:01 UTC, MarioLozanoM requested changes

2023-04-06 06:01 UTC, MarioLozanoM commented on src/ui/components/NotFoundView.tsx
Este archivo debería estar en una carpeta también, todas las views están en carpetas, no debe quedar una suelta

2023-04-06 06:01 UTC, MarioLozanoM commented on src/ui/components/common/NavBar.tsx
@angieAGL esto no lo has corregido

2023-04-06 06:01 UTC, MarioLozanoM commented on src/ui/css/errorView.css
al otro le cambiaste de nombre pero a este no

2023-04-06 22:44 UTC, angieAGL commented on src/ui/components/common/NavBar.tsx
Si lo hice, solo que el cambio es el sidebar no el navbar, y ya arregle lo que te paso

2023-04-08 01:53 UTC, MarioLozanoM approved these changes

2023-04-08 01:53 UTC, merged